require("settings/error")
require("settings/config")
require("settings/auto")
require("settings/layout")
require("settings/wibox")
require("settings/bindings")
require("settings/rules")
require("settings/signals")
