require("settings/error")
require("settings/functions")
require("settings/config")
require("settings/tags")
require("settings/wibox")
require("settings/bindings")
require("settings/rules")
require("settings/signals")
